name: CI

on: 
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
      # 1. Repository ausschecken
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Python 3.11 installieren
      - name: Setup Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # 3. Abhängigkeiten installieren
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      # 4. Lint-Check mit Ruff
      - name: Ruff-Lint
        run: ruff check .

      - name: Ruff-Format-Check
        run: ruff format --check .

      # 5. Statistisches Type-Checking mit mypy
      - name: Type-Check
        run: mypy src

      # 6. (Leere) Unit-Tests ausführen
      - name: Unit-Tests
        run: |
          pytest -q || if [ $? -eq 5 ]; then echo "No tests collected – OK for now"; exit 0; fi